set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_C_COMPILER /usr/bin/aarch64-unknown-linux-gnu-gcc)
set(CMAKE_CXX_COMPILER /usr/bin/aarch64-unknown-linux-gnu-g++)
set(CMAKE_FIND_ROOT_PATH /usr/aarch64-unknown-linux-gnu)
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)